<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile
?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
$element                 = $this->getData('cpb_element');
$productName             = $element->getData('product_name');
$productPrice            = $element->getData('product_price');
$productImage            = $element->getData('product_image');
$productReview           = $element->getData('product_review');
$productAddtocart        = $element->getData('product_addtocart');
$productShortdescription = $element->getData('product_shortdescription');
$productWishlist         = $element->getData('product_wishlist');
$productCompare          = $element->getData('product_compare');
$productSwatches         = $element->hasData('product_swatches') ? $element->getData('product_swatches') : true;
$mode                    = $block->getMode();
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($mode == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
            <li class="item product product-item">
                <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php if ($productName) { ?>
                            <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                        <?php } ?>
                        <!-- Begin eTrusted widget tag -->
<etrusted-widget data-etrusted-widget-id="wdg-e2c875ed-22d9-4713-a2d2-f9a3b93bca40" data-sku="<?= $block->escapeHtml($_product->getSku()) ?>"></etrusted-widget>
<!-- End eTrusted widget tag -->
                        <?php if ($productReview) { ?>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?php } ?>
                        <?php if ($productPrice) { ?>
                            <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <?php } ?>

                        <?php if ($productSwatches) { ?>
                            <?= $block->getProductDetailsHtml($_product) ?>
                        <?php } ?>

                        <?php if ($productAddtocart || $productWishlist || $productCompare || $productShortdescription) { ?>
                        <div class="product-item-inner">
                            <?php if ($productAddtocart || $productWishlist || $productCompare) { ?>
                            <div class="product actions product-item-actions"<?= strpos($pos ?? '', $viewMode . '-actions') ? $position : '' ?>>
                                <?php if ($productAddtocart) { ?>
                                    <div class="actions-primary"<?= strpos($pos ?? '', $viewMode . '-primary') ? $position : '' ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                                <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                                <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
                                                    <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->isAvailable()): ?>
                                                <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                <?php } ?>
                                <?php if ($productWishlist || $productCompare) { ?>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos ?? '', $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($productWishlist) { ?>
                                        <a href="#"
                                            class="action towishlist"
                                            title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                            aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>"
                                            data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_product) ?>'
                                            data-action="add-to-wishlist"
                                            role="button">
                                            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                        </a>
                                    <?php } ?>
                                    <?php if ($productCompare) { ?>
                                        <a href="#"
                                            class="action tocompare"
                                            title="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                                            aria-label="<?= $block->escapeHtml(__('Add to Compare')) ?>"
                                            data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_product) ?>'
                                            role="button">
                                            <span><?= /* @escapeNotVerified */ __('Add to Compare') ?></span>
                                        </a>
                                    <?php } ?>
                                </div>
                                <?php } ?>
                            </div>
                            <?php } ?>
                            <?php if ($productShortdescription) { ?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php } ?>
                        </div>
                        <?php } ?>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
